# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-07 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atmb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('order_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Site_Check_BasicItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('weather', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('thunderbolt_day', models.CharField(max_length=50)),
                ('thunderbolt_protect_level', models.CharField(max_length=50)),
                ('power_ground_mode', models.CharField(max_length=50)),
                ('check_engineer', models.CharField(max_length=50)),
                ('site_overview', models.CharField(max_length=50)),
                ('memo', models.CharField(max_length=50)),
                ('report_suggestion', models.CharField(max_length=50)),
                ('atmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Atmb')),
            ],
        ),
        migrations.CreateModel(
            name='Site_Check_SpotPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_picture', models.ImageField(upload_to='upload/spotPicture')),
                ('site_check_basicItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Site_Check_BasicItem')),
            ],
        ),
        migrations.CreateModel(
            name='Site_Check_SysTopology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_topology', models.FileField(upload_to='upload/sysTopology')),
                ('site_check_basicItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Site_Check_BasicItem')),
            ],
        ),
        migrations.CreateModel(
            name='Site_Check_ThunderHitEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thunder_hitDate', models.DateField()),
                ('thunder_hitAnalysis', models.FileField(blank=True, null=True, upload_to='upload/thunderHitAnalysis')),
                ('thunder_rectifyAction', models.FileField(blank=True, null=True, upload_to='upload/thunderRectifyAction')),
                ('site_check_basicItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Site_Check_BasicItem')),
            ],
        ),
        migrations.CreateModel(
            name='Site_Check_ThunderProtectPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thunder_protectPlan', models.FileField(upload_to='upload/thunderProtectPlan')),
                ('site_check_basicItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Site_Check_BasicItem')),
            ],
        ),
        migrations.CreateModel(
            name='WireShield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipotential_mode', models.CharField(max_length=5)),
                ('meb_des', models.CharField(max_length=50)),
                ('meb_value', models.IntegerField()),
                ('leb_des', models.CharField(max_length=50)),
                ('leb_value', models.IntegerField()),
                ('has_antistatic_floor', models.BooleanField(default=False)),
                ('is_bracket_under_ground', models.BooleanField(default=False)),
                ('equipment_ground_star', models.IntegerField()),
                ('shelf_ground_start', models.IntegerField()),
                ('earth_wire_star', models.IntegerField()),
                ('misc_star', models.IntegerField()),
                ('equipotential_memo', models.CharField(max_length=50)),
                ('has_idc_shield', models.BooleanField(default=False)),
                ('idc_shield_des', models.CharField(max_length=50)),
                ('has_shelf_shield', models.BooleanField(default=False)),
                ('shelf_shield_des', models.CharField(max_length=50)),
                ('has_line_shield', models.BooleanField(default=False)),
                ('line_shield_des', models.CharField(max_length=50)),
                ('shield_memo', models.CharField(max_length=50)),
                ('has_wire', models.BooleanField(default=False)),
                ('is_wire1_proper', models.BooleanField(default=False)),
                ('is_wire2_proper', models.BooleanField(default=False)),
                ('is_wire3_proper', models.BooleanField(default=False)),
                ('wire_memo', models.CharField(max_length=50)),
                ('atmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Atmb')),
            ],
        ),
    ]
