# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-09 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireshield',
            name='earth_wire_star',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='equipment_ground_star',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='equipotential_memo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='equipotential_mode',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('Ss', 'Ss'), ('Mm', 'Mm')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='idc_shield_des',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='leb_des',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='leb_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='line_shield_des',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='meb_des',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='meb_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='misc_star',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='shelf_ground_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='shelf_shield_des',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='shield_memo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='wire_memo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
