# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-09 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atmb', '0002_auto_20160609_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireshield',
            name='atmb',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atmb.Atmb'),
        ),
    ]
