# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-12 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atmb', '0003_auto_20160609_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Down_Lead_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('spec', models.CharField(blank=True, max_length=50, null=True)),
                ('resistance', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('distance_away_cable', models.IntegerField(blank=True, choices=[(0, '>='), (1, '<')], null=True)),
                ('cable_quantity', models.IntegerField(blank=True, null=True)),
                ('check_result', models.IntegerField(blank=True, choices=[(0, '合格'), (1, '不合格')], null=True)),
                ('atmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Atmb')),
            ],
        ),
        migrations.CreateModel(
            name='Earth_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(blank=True, choices=[(0, '自然接地体'), (1, '人工接地体'), (2, '联合接地装置')], null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('resistance', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('construction_date', models.IntegerField(blank=True, null=True)),
                ('check_result', models.IntegerField(blank=True, choices=[(0, '合格'), (1, '不合格')], null=True)),
                ('atmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Atmb')),
            ],
        ),
        migrations.CreateModel(
            name='Lightning_Receptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_device', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('resistance', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('check_result', models.IntegerField(blank=True, choices=[(0, '合格'), (1, '不合格')], null=True)),
                ('atmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Atmb')),
            ],
        ),
        migrations.CreateModel(
            name='Thunder_External_Protect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=50)),
                ('atmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Atmb')),
            ],
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='earth_wire_star',
            field=models.IntegerField(blank=True, null=True, verbose_name='地线长度/颜色/线径综合评定'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='equipment_ground_star',
            field=models.IntegerField(blank=True, null=True, verbose_name='设备接地'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='equipotential_memo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注（待确认后，自动同去步到常规项的备注中）:'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='equipotential_mode',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('Ss', 'Ss'), ('Mm', 'Mm')], max_length=2, null=True, verbose_name='等电位形式'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='has_antistatic_floor',
            field=models.BooleanField(default=False, verbose_name='抗静电地板'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='has_idc_shield',
            field=models.BooleanField(default=False, verbose_name='机房屏蔽'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='has_line_shield',
            field=models.BooleanField(default=False, verbose_name='线缆屏蔽'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='has_shelf_shield',
            field=models.BooleanField(default=False, verbose_name='机柜屏蔽'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='has_wire',
            field=models.BooleanField(default=False, verbose_name='弱电电缆-金属线线槽/管道'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='is_wire1_proper',
            field=models.BooleanField(default=False, verbose_name='电磁感应环路面积合理'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='is_wire2_proper',
            field=models.BooleanField(default=False, verbose_name='与避雷引下线距离合理'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='is_wire3_proper',
            field=models.BooleanField(default=False, verbose_name='强弱电电缆敷设距离合理'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='leb_des',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='LEB描述'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='leb_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='LEB描述'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='meb_des',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MEB描述'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='meb_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='MEB值'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='misc_star',
            field=models.IntegerField(blank=True, null=True, verbose_name='铠(屏蔽)层/光缆钢芯、冗余线、金属管道、消防柜、电池柜'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='shelf_ground_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='机柜接地'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='shield_memo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注（待确认后，自动同去步到常规项的备注中）:'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='wire_memo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注（待确认后，自动同去步到常规项的备注中）:'),
        ),
    ]
