# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-04 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atmb', '0005_auto_20160619_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeder_Line_SPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='型号')),
                ('Uc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Uc')),
                ('In', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='In')),
                ('Up', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Up')),
                ('ground_wire_len', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='地线长度')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='安装日期')),
                ('install_place', models.CharField(max_length=50, verbose_name='安装位置')),
                ('check_result', models.IntegerField(blank=True, choices=[(0, '合格'), (1, '不合格')], null=True, verbose_name='检查结论')),
                ('atmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Atmb')),
            ],
        ),
        migrations.CreateModel(
            name='Power_SPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, choices=[(0, '复合型SPD'), (1, '1级SPD'), (2, '2级SPD'), (3, '3级SPD'), (4, '自带SPD'), (5, '直流SPD')], null=True, verbose_name='类别')),
                ('type', models.CharField(max_length=50, verbose_name='型号')),
                ('Uc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Uc')),
                ('In', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='In')),
                ('Up', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Up')),
                ('main_circuit_a', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='主电路空开')),
                ('main_circuit_p', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('backup_protection_a', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='后备保护')),
                ('backup_protection_p', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('wiring_total_len', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='接线总长')),
                ('payload', models.BooleanField(default=False, verbose_name='负载')),
                ('onsite_test', models.BooleanField(default=False, verbose_name='现场测试')),
                ('pressure_1_v', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='压1')),
                ('pressure_1_ua', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('pressure_2_v', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='压2')),
                ('pressure_2_ua', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('pressure_3_v', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='压3')),
                ('pressure_3_ua', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('pressure_4_v', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='压4')),
                ('pressure_4_ua', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='安装日期')),
                ('install_place', models.CharField(max_length=50, verbose_name='安装位置')),
                ('check_result', models.IntegerField(blank=True, choices=[(0, '合格'), (1, '不合格')], null=True, verbose_name='检查结论')),
                ('atmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Atmb')),
            ],
        ),
        migrations.CreateModel(
            name='Signal_SPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, choices=[(0, '复合型SPD'), (1, '1级SPD'), (2, '2级SPD'), (3, '3级SPD'), (4, '自带SPD'), (5, '直流SPD')], null=True, verbose_name='类别')),
                ('type', models.CharField(max_length=50, verbose_name='型号')),
                ('Uc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Uc')),
                ('In', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='In')),
                ('Up', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Up')),
                ('ground_wire_len', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='地线长度')),
                ('payload', models.BooleanField(default=False, verbose_name='负载')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='安装日期')),
                ('install_place', models.CharField(max_length=50, verbose_name='安装位置')),
                ('protection_device', models.CharField(max_length=50, verbose_name='保护设备')),
                ('check_result', models.IntegerField(blank=True, choices=[(0, '合格'), (1, '不合格')], null=True, verbose_name='检查结论')),
                ('atmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Atmb')),
            ],
        ),
        migrations.CreateModel(
            name='SPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=50, verbose_name='备注')),
                ('atmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmb.Atmb')),
            ],
        ),
    ]
