# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmb', '0006_feeder_line_spd_power_spd_signal_spd_spd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder_line_spd',
            name='install_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='安装位置'),
        ),
        migrations.AlterField(
            model_name='feeder_line_spd',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='power_spd',
            name='install_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='安装位置'),
        ),
        migrations.AlterField(
            model_name='power_spd',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='signal_spd',
            name='install_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='安装位置'),
        ),
        migrations.AlterField(
            model_name='signal_spd',
            name='protection_device',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='保护设备'),
        ),
        migrations.AlterField(
            model_name='signal_spd',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='型号'),
        ),
    ]
