# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-04 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmb', '0007_auto_20160704_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spd',
            name='memo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注'),
        ),
    ]
