# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-09 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmb', '0008_auto_20160704_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earth_device',
            name='construction_date',
            field=models.DateField(blank=True, null=True, verbose_name='建设日期'),
        ),
    ]
