# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-09 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmb', '0009_auto_20160709_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireshield',
            name='earth_wire_star',
            field=models.IntegerField(blank=True, choices=[(0, '一星'), (1, '二星'), (2, '三星'), (3, '四星'), (4, '五星')], null=True, verbose_name='地线长度/颜色/线径综合评定'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='equipment_ground_star',
            field=models.IntegerField(blank=True, choices=[(0, '一星'), (1, '二星'), (2, '三星'), (3, '四星'), (4, '五星')], null=True, verbose_name='设备接地'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='misc_star',
            field=models.IntegerField(blank=True, choices=[(0, '一星'), (1, '二星'), (2, '三星'), (3, '四星'), (4, '五星')], null=True, verbose_name='铠(屏蔽)层/光缆钢芯、冗余线、金属管道、消防柜、电池柜'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='shelf_ground_start',
            field=models.IntegerField(blank=True, choices=[(0, '一星'), (1, '二星'), (2, '三星'), (3, '四星'), (4, '五星')], null=True, verbose_name='机柜接地'),
        ),
    ]
