# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-10 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmb', '0010_auto_20160709_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmb',
            name='order_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='atmb',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='down_lead_line',
            name='cable_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='1米'),
        ),
        migrations.AlterField(
            model_name='down_lead_line',
            name='check_result',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '合格'), (1, '不合格')], null=True, verbose_name='检查结论'),
        ),
        migrations.AlterField(
            model_name='down_lead_line',
            name='distance_away_cable',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '>='), (1, '<')], null=True, verbose_name='与电缆水平距离'),
        ),
        migrations.AlterField(
            model_name='down_lead_line',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='down_lead_line',
            name='resistance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='接地电阻'),
        ),
        migrations.AlterField(
            model_name='earth_device',
            name='check_result',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '合格'), (1, '不合格')], null=True, verbose_name='检查结论'),
        ),
        migrations.AlterField(
            model_name='earth_device',
            name='mode',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '自然接地体'), (1, '人工接地体'), (2, '联合接地装置')], null=True, verbose_name='形式'),
        ),
        migrations.AlterField(
            model_name='earth_device',
            name='resistance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='接地电阻'),
        ),
        migrations.AlterField(
            model_name='feeder_line_spd',
            name='check_result',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '合格'), (1, '不合格')], null=True, verbose_name='检查结论'),
        ),
        migrations.AlterField(
            model_name='feeder_line_spd',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='lightning_receptor',
            name='check_result',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '合格'), (1, '不合格')], null=True, verbose_name='检查结论'),
        ),
        migrations.AlterField(
            model_name='lightning_receptor',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='lightning_receptor',
            name='resistance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='接地电阻'),
        ),
        migrations.AlterField(
            model_name='power_spd',
            name='category',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '复合型SPD'), (1, '1级SPD'), (2, '2级SPD'), (3, '3级SPD'), (4, '自带SPD'), (5, '直流SPD')], null=True, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='power_spd',
            name='check_result',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '合格'), (1, '不合格')], null=True, verbose_name='检查结论'),
        ),
        migrations.AlterField(
            model_name='power_spd',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='signal_spd',
            name='category',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '复合型SPD'), (1, '1级SPD'), (2, '2级SPD'), (3, '3级SPD'), (4, '自带SPD'), (5, '直流SPD')], null=True, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='signal_spd',
            name='check_result',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '合格'), (1, '不合格')], null=True, verbose_name='检查结论'),
        ),
        migrations.AlterField(
            model_name='signal_spd',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='earth_wire_star',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '一星'), (1, '二星'), (2, '三星'), (3, '四星'), (4, '五星')], null=True, verbose_name='地线长度/颜色/线径综合评定'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='equipment_ground_star',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '一星'), (1, '二星'), (2, '三星'), (3, '四星'), (4, '五星')], null=True, verbose_name='设备接地'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='leb_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='LEB描述'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='meb_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MEB值'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='misc_star',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '一星'), (1, '二星'), (2, '三星'), (3, '四星'), (4, '五星')], null=True, verbose_name='铠(屏蔽)层/光缆钢芯、冗余线、金属管道、消防柜、电池柜'),
        ),
        migrations.AlterField(
            model_name='wireshield',
            name='shelf_ground_start',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '一星'), (1, '二星'), (2, '三星'), (3, '四星'), (4, '五星')], null=True, verbose_name='机柜接地'),
        ),
    ]
